name: "Build T875 Kernel"
on:
  push:
    branches: '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Windstation Kernel
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
            sudo apt update
            sudo sudo apt install build-essential bc flex bison libncurses5-dev libssl-dev git ccache python2

      - name: Build kernel
        run: |
            sh kernel_build.sh

      - name: Package kernel
        run: |
            sh kernel_package.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v2
        with:
          name: Windstation Kernel
          path: release/Windstation.zip
